name: Python CI


on:
  push:
    branches:
        - main
        - develop
  pull_request:
    branches:
      - main

run-name: Run by ${{ github.actor }} on commit ${{ github.sha }}

env:
  PYTHON_VERSION: 3.10

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage flake8

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s app

      - name: Show coverage report
        run: |
          coverage report -m

      - name: Flake8 code style check (non-blocking)
        continue-on-error: true
        run: |
          flake8 app

      - name: Flake8 complexity check (non-blocking)
        continue-on-error: true
        run: |
          flake8 --max-complexity=10 app

      - name: Upload Python code artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-code
          path: |
            app/**/*.py